### PR TITLE
updated SQLite to 3.8.9 from 3.8.5

### PR DESCRIPTION
**Pull request by ariccio**
downloaded, extracted, and replaced old version with files from SQLite 3.8.9 (released April 8th, 2015)

...hence the changeset ***looks*** huge, but *I, personally, didn't change a single line*.

### CODE REVIEW

**Comment by donho** [comment]
Thank you for the update... but what is the reason of this update?

**Comment by ariccio** [comment]
I'm not sure that I understand your question?

[This is a regularly scheduled maintenance release](https://www.sqlite.org/news.html).

**Comment by MAPJe71** [comment]
*Don't fix it when it ain't  broken.*

**Comment by ariccio** [comment]
- There are a bunch of improved debugging/reliability features (e.g. SQLITE_ENABLE_API_ARMOR), and *many* small bugfixes. One bug was encountered by "a prominent SQLite user", and was serious enough to justify a rushed fix.
- This is not a breaking change, if the behavior of Notepad++ changes in any (negative) way, *then Notepad++ is broken,* ***by definition***.

**Comment by donho** [comment]
Notepad++ use a small part of functionalities of SQLite. While there is no bug on this part so far, I don't see any reason to take the risk having regression to update whole SQLite.

**Comment by ariccio** [comment]
Grr. Ok.

**Pull request closed without merging**
