### PR TITLE
Enable multiprocessor build

### PR DESCRIPTION
**Pull request by rcdailey**
Project now utilizes the `/MP` compiler switch to perform parallelized builds. The number of parallel builds performed is determined on a per-machine basis based on available logical CPUs.

Long term this will provide the best performance output to code maintainability ratio compared to just enabling precompiled headers.

Using my personal machine (8 cores), I got the following timings (Debug configuration):

* Normal build: 89 seconds
* Multi-processor build: 28 seconds
* PCH enabled: 27 seconds

Note that the multi-processor build timings can be further reduced with proper dependency management and removal of existing precompiled header file (precompiledHeaders.h).

Also please note that this PR should be accepted in lieu of PR #78 which would (in contrast to what I'm proposing) enable precompiled headers which have long term impact on the maintainability of the code base (dependency management).

Specific Changes:

* Precompiled header support disabled (not compatible with `/MP` flag).
* precompiledHeader.cpp deleted.
* Solution File added.
* Minimal Rebuild (`/Gm`) disabled (ignored when `/MP` is on).

precompiledHeaders.h still exists because it contains a ton of inclusions required by lots of files. A second and less trivial cleanup will involve removing the precompiledHeaders.h file and individually correcting and satisfying dependencies in each source file in the code base.

### CODE REVIEW

**Comment by NN---** [comment]
Please restore the runtime /MT , otherwise people must install VC redistributable and it is painful.

**Comment by rcdailey** [comment]
@NN--- I will restore it in this PR because it is unrelated to the topic change.

However I believe Notepad++ should not statically link the runtimes. The installer should be updated to silently install the redistributable if necessary.

I will make that a separate pull request.

**Comment by NN---** [comment]
Why ? What Dynamic runtime gives you over static?
It doesn't add performance or make less bugs, but it does make installer complex and management of runtimes.

**Comment by rcdailey** [comment]
@NN--- There are a [bunch of reasons to prefer DLLs](http://stackoverflow.com/questions/757418/should-i-compile-with-md-or-mt) over static linking the runtimes. I won't go over all of them here (feel free to read the SO post, it's very informative).

The benefits of static linking become less useful when you have an installer that can transparently setup redistributables anyway. So it's a no-brainer to choose DLL for runtime, IMHO.

We can discuss in more detail in a related PR later, if you wish. You've made a good point about reverting the runtime change here, so I have done that to keep the PR focused.

**Comment by NN---** [comment]
I am familiar with advantages and disadvantages.
The question what we solve with that.
I don't see currently any problem with static linking.
Updates to runtime are for good and for bad, sometimes small behavior changes and program breaks:)

It will definitely make installer bigger about by 3MB (if I remember correctly this is size of redistributable) and with 64bit it will add another ones.

**Comment by NN---** [comment]
My measurements for Release build.

PCH: 1:10
Multiprocess: 1:20

It is still much better then before :)

**Comment by rcdailey** [comment]
@NN--- Again I do not want to discuss static/dynamic runtime linking here, I am shelving that discussion for another time.

The build time for multi-process will significantly improve even further after the elimination of `precompiledHeaders.h`. Doing so will mean translation units include only what they need instead of the same set of tens of files being compiled over and over again.

**Comment by NN---** [comment]
There are no tons of includes in the project.
Actually, in Windows PCH helps because you almost always includes windows.h and it is a very large include file.

**Comment by rcdailey** [comment]
@NN--- I don't know why I have to go over basic arguments with you. Look at `precompiledHeaders.h` Every single one of those includes are being compiled per translation unit that includes it (that's everything or close to it). Not every translation unit requires all the headers that `precompiledHeaders.h` includes.

Anyway this is a bigger second cleanup phase. Not worth going into detail right now.

**Comment by NN---** [comment]
Okay :)
I am closing my PR and waiting for this to be merged.

**Comment by NN---** [comment]
Btw, can you please measure time of Precompiled headers with multiprocess enabled ?
Thanks.

**Comment by rcdailey** [comment]
Precompiled headers may not be enabled with parallel builds.

**Comment by NN---** [comment]
Why not ?
Just go to menu and enable multiprocess build.
It doesn't say me that it can't do it.

**Comment by NN---** [comment]
It is just interesting to see whether PCH with MP have a noticeable difference.

**Comment by rcdailey** [comment]
@NN--- When you compile you will get a warning from the compiler that PCH are ignored.

**Comment by NN---** [comment]
Oh, you are right :)
Missed that.

**Comment by donho** [comment]
1:42 (vs 1:13) on my 32 bits machine. Obviously my cpu can be classified as prehistoric one (Intel core duo 3.16 Ghz).

I agree with @NN--- - I prefer /MT than /MD, so installer can be smaller and users install/launch Notepad++ without any error message.

**Pull request merged**
