### PR TITLE
Remove binary file

### PR DESCRIPTION
**Pull request by NN---**
Pdb file is not intended to be committed

### CODE REVIEW

**Comment by andreas-jonsson** [comment]
The PDB is committed for every release, and it is useful if someone sends a dump file.

**Comment by NN---** [comment]
This file shouldn't be in the repository.
Put it on symbols server with the source and then you can debug without checking out .
For instance this site provides the service: http://www.symbolsource.org/

You put there sources with all pdbs for the release version and then anyone can add the server to symbols path .

**Comment by NN---** [comment]
ave also github large files git extension for storing binary files like this one.

**Comment by rcdailey** [comment]
+1

**Comment by Rikk** [comment]
Also, /bin folder contains DLLs/EXEs. I know projects usually don't hold compiled binaries, instead they use references to original repositories, so when you compile Npp you also compile sub-projects, thus creating these binaries.

**Pull request merged**
