### PR TITLE
Optimize font quality for LCD

### PR DESCRIPTION
**Pull request by jay1109**
I can add a screenshot, if you want to see the difference.

### CODE REVIEW

**Comment by andreas-jonsson** [comment]
I think a screenshot would be good. I tried this PR the last time it was suggested, but I couldn't see any changes.

**Comment by damien-gerard** [comment]
A screenshot is always welcome for this kind of change :)

**Comment by donho** [comment]
@jay1109  Could you show us the screenshot please?

**Comment by jay1109** [comment]
The screenshot of the change:
(Sorry for the late reply.)

npp-with-change
npp-without-change

**Comment by jay1109** [comment]
second example

with change:
npp-with-change-2
without change:
npp-without-change-2

**Comment by ariccio** [comment]
Awesome :)

**Comment by Yaron10** [comment]
https://sourceforge.net/p/notepad-plus/discussion/331754/thread/59cc8389

**Comment by bogiord** [comment]
As indicated by Yaron10 in the referenced discussion, the problem with this change is that it unconditionally enables ClearType even for those of us who disabled it system-wide. Notepad++ should either replicate the global settings or at least allow us to configure this through the Preferences dialog.

**Comment by Yaron10** [comment]
Hello DmFedorov,

I hope this issue would be resolved in the next version.
A workaround for v6.7.9:

Install the Notepad++ Python Script plugin.
http://sourceforge.net/projects/npppythonscript/ 

Add the following lines to the file startup.py.
editor1.setFontQuality(0)
editor2.setFontQuality(0)

Open Python Script -> Configuration.
Set Initialization to ASTARTUP.

Best regards.

python

**Comment by jonandr** [comment]
See #311.

**Pull request merged**
