### PR TITLE
Add .gitattributes file and normalize all line endings

### PR DESCRIPTION
**Pull request by rcdailey**
When you imported your SVN repository to Git, you did not normalize line endings. Git does a lot of line ending normalization that SVN never did. Normally a direct import of SVN code base into Git will retain original CRLF line endings on Windows. This pull request modifies every single file in the repository to normalize line endings. That is the only change here.

Please see this article for information regarding line ending handling:
https://help.github.com/articles/dealing-with-line-endings/

I really recommend you accept this PR as without this change, you will be constantly fighting Git on line ending settings and each developer's git configuration will determine line endings they commit, which will result in weird diffs and inconsistencies.

### CODE REVIEW

**Comment by andreas-jonsson** [comment]
I don't suppose there is some kind of advanced Git magic which would allow this to be merged but without messing up the history (blame in particular)?

**Comment by rcdailey** [comment]
Yeah you can do git filter-branch, but you will be rewriting history. It means you'll have to rebase any feature branches and forks to be remade/forcibly synced afterwards but isn't too bad.

**Comment by rcdailey** [comment]
Here is more information:
http://blog.gyoshev.net/2013/08/normalizing-line-endings-in-git-repositories/

Note that using `git filter-branch --tree-filter` is very very time consuming especially for large repos. It's something you may have to leave running overnight.

**Comment by cmeriaux** [comment]
+1

**Comment by MAPJe71** [comment]
+1

**Comment by rcdailey** [comment]
Sorry for another successive post:

I am happy to do the filter-branch for you (if you'd rather go that route), however I wouldn't be able to do it with the pull request model. I could do it on a local clone. I'll zip the clone and send it to you, and leave it up to you to force-push the master branch over what you have now.

Let me know what you decide (especially want feedback from @donho).

**Comment by cmeriaux** [comment]
Git blame is not a problem. Add the option -w to ignore whitespace and line ending.

**Comment by ariccio** [comment]
+1 :+1: The sooner we fix this, the less pain we'll have to endure.

**Comment by donho** [comment]
@rcdailey Basically I'm for your pr.
I'm quite confused by the modification you made in commit "Normalize all line endings". I cannot see the different line endings from the diff. What did you change exactely? From LF to CRLF?

**Comment by rcdailey** [comment]
@donho You can't rely on github to show you the true diff, I don't believe.

My commit removes all carriage returns from files that had them (0x0D). Internally, git likes to store files with only line-feed characters (LF). The .gitattributes file will assist in making sure files in your **working copy** contain CRLF on windows, and when you commit them, the CRLF is transparently converted back to LF for storage in the repository.

Basically there is this constant transition between LF and CRLF on Windows:

When you checkout, it goes from LF -> CRLF
When you commit, it goes from CRLF -> LF

This only applies to text files matched under `* text=auto` in the .gitattributes file. You can override files to always have LF on checkout (no conversion) by doing `mybashscript.sh eol=lf`.

To see the actual line ending changes in a diff, you'd have to check out the branch or PR and do:

    $ git diff -R HEAD^

`-R` will show you the reverse of the diff (it will show you the conversion from LF -> CRLF). Git will never show LF in diffs, only CR. And it will only show CR (0x0D) when it is introduced not removed. That's why `-R` is necessary here; to see a diff where CR is introduced (I removed it in my diff, so naturally we need to reverse the diff to see it).

**Comment by rcdailey** [comment]
@donho I've just rebased this branch onto latest in `master`. Each time master changes, I have to rebase my branch again. So I hope you will merge this soon.

**Comment by donho** [comment]
@rcdailey Sorry for the late reply.
I will only accept "Add .gitattributes file".
However, I checked line ending in question mentioned in "Normalize all line endings", I see no problem (they are all CRLF). Therefore there's no reason for me to accept "Normalize all line endings", for the following reasons:
1. I have no idea what are changed in these files.
2. that will break "blame" feature.

I will close this pr.
Could you do another one with only "Add .gitattributes file" please?
Sorry for the inconvenience.

**Comment by rcdailey** [comment]
@donho You are wrong on several points.

* Git blame will still function (use `-w` option), as indicated earlier on by someone else.
* Why are you saying you "don't know what changed in these files"? I just explained it to you. There is nothing but line ending changes.
* The line endings are stored as CRLF *inside* the repository right now. **This is incorrect!**. They are supposed to be LF inside the repo, and the `.gitattributes` will convert them to CRLF on checkout as needed. This is how all git repositories work with proper `.gitattributes` files.
* Accepting only the `.gitattributes` will create no end to headache for you. Files will show up as modified when you didn't change them, because git is converting line endings. That is why you need to normalize line endings all at once to avoid this.

Don, I have explained everything in great detail in my posts throughout this pull request. It is obvious to me you have not read any of this, because of the statements you are making which are untrue.

Please go back and read everything, especially the articles I linked. I encourage you to reopen this PR and merge it properly.

**Comment by ariccio** [comment]
>  is obvious to me you have not read any of this

@rcdailey I understand (and, to some degree, share) your frustration, but please refrain from *ad hominem* attacks ("attack" might not be the best word), as they're counterproductive.

Instead of just saying "you are wrong"/'`git blame` will still work', provide evidence that it does. No *specific* format is necessary, be it a screenshot, text of a shell session, or a video, is constructive (and educational) for all involved.

> I just explained it to you

Linking to said explanation also helps :)

> Please go back and read everything [...]

Specificity, as before, helps.

**Comment by rcdailey** [comment]
@ariccio Read the thread. You are asking for links/etc but it's all here. I can't make it any easier for you.

And there is no attack going on here. Simply stating the facts. All I'm asking people to do is just read.

**Comment by donho** [comment]
@rcdailey 
If it MUST be LF as line ending in the git repo, it'll be my job to transfer all CRLF to LF, but not some-else.
Please don't take it personally - that's the interest of code review.
I will read these links again I promise you, and I will be back to you soon.

**Comment by ariccio** [comment]
> You are asking for links/etc but it's all here.

Nonono it's not for *my* benefit, but in this case it's specifically for @donho


> And there is no attack going on here.

Yeah sorry, "attack" was the wrong word. I did however sense a degree of frustration, which is not an optimal way of conveying thoughts over the internet.

> Why are you saying you "don't know what changed in these files"? There is nothing but line ending changes.


Perhaps they are *legitimately not showing up for him*. Whatever the actual reason, if you tell him something that's obviously not true (*to him*, as

**Comment by ariccio** [comment]
*shit, I didn't mean to hit "Comment"*

**Comment by ariccio** [comment]
[continued from where I prematurelyposted].... as is the flaw in aristotelian logic/epistemology), (i.e. "there's [something] on your screen! If you can't see it, look harder!", when said thing is not actually visible), he's just going to tire of the whole thing, and stop paying attention to you.

**Comment by milipili** [comment]
Git will not convert line endings if you don't ask for it (not configured for it). pull/push "as it" is probably the way to go, as it is done in so many projects and it is by personnal experience less error prone. If files are modified because of that, i would say that the issue may come from some bad habits (especially on windows) to perform nasty file convertions on the fly because some old editors were not able to handle such cases. I understand however this can be handy in some situations, but it is probably a different point of view.

Anyway, whatever the personnal feelings or the state of the repository, a PR is obviously not be the appropriate way for this kind of changes. You can not say "hurry up take my changes !". I am quite confident you would not do it IRL. A ticket would be far better, to open a discussion for a proposal before providing some major changes, which may not be properly merged at the time of acceptance (other things may have a highest priority). It will save time for everyone.

**Comment by rcdailey** [comment]
I've had enough experience with line ending issues and done enough hours of research on it to basically "know what's best", although I understand the "Just trust me" mentality doesn't get accepted very well.

I just want everyone to know I have good intentions here and I do not intend to rush the issue as some people think. 

I agree that a PR is one of the less effective ways to get this change in but I did so anyway, leaving the call up to @donho. If it were me personally I would do the history rewrite. I did that for several SVN conversions to Git and it's the best way to go if you catch it early enough. As I've said all along, the harm is in that the repository has already gone public and there will be some collateral damage.

On the other hand, forcibly dealing with the whitespace change in history can be a pain as well even though there are "ignore whitespace" options available. You'd need to be consciously aware of it and make sure to specify the correct parameters. This could get annoying for those less familiar with the actual history of the repository.

@milipili Slight correction to your explanation. Git will convert line endings per users configuration if there is no `.gitattributes`. That means that there is potential for confusing and seemingly superfluous diffs in pull requests on a per-user basis due to line ending conversions. It puts the burden on the contributors instead of the issue being handled transparently and most importantly *consistently* by having a `.gitattributes` file.

My apologies if I sounded frustrated; unfortunately my tone does not carry well through text so I can understand where I would sound pushy/frustrated. In any case, per Don's request I shall remove the line ending normalization commit and leave the `.gitattributes` file. I will let him decide how to perform the line ending normalization based on the collective information I've provided.

@donho I'm available for questions if you have any!

Thanks everyone for the feedback and discussion.

**Pull request closed without merging**
