### PR TITLE
Merge with 'upstream/master'

### PR DESCRIPTION
**Pull request by MAPJe71**

### CODE REVIEW

**Comment by MAPJe71** [comment]
Oops! wrong direction

**Comment by ariccio** [comment]
hahaha that's a whoops...... Trying to sync up? If so, why were you trying to use a pull request to sync up? That's how I did it when I first started using Git, but you'll find out that it's a pretty terrible way to do things.

Here's how I do it (copied and pasted from `Git Shell`):

```
Welcome to Portable Git (version ghfw)


Run 'git help git' to display the help index.
Run 'git help <command>' to display help for specific commands.

AlexanderRiccio@ALEXANDERLAPTOP ~/Documents/GitHub/notepad-plus-plus (master)
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean

AlexanderRiccio@ALEXANDERLAPTOP ~/Documents/GitHub/notepad-plus-plus (master)
$ git status
On branch donho/master
Your branch is behind 'remotes/donho/master' by 26 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)

nothing to commit, working directory clean

AlexanderRiccio@ALEXANDERLAPTOP ~/Documents/GitHub/notepad-plus-plus (donho/master)
$ git pull --verbose
From https://github.com/donho/notepad-plus-plus
 = [up to date]      master     -> donho/master
 = [up to date]      pr/35      -> donho/pr/35
 = [up to date]      pr/44      -> donho/pr/44
Updating c3c0cc4..5c272a8
Fast-forward
 .gitignore                                         |    1 +
 PowerEditor/bin/change.log                         |   20 +-
 PowerEditor/bin/readme.txt                         |   12 +-
 PowerEditor/bin/updater/GUP.exe                    |  Bin 135168 -> 135168 bytes
 PowerEditor/bin/updater/License.txt                |  165 --
 PowerEditor/bin/updater/gup.xml                    |   43 +-
 PowerEditor/bin/updater/libcurl.dll                |  Bin 262144 -> 288256 bytes
 PowerEditor/bin/updater/readme.txt                 |   60 -
 PowerEditor/installer/nativeLang/czech.xml         |   70 +-
 PowerEditor/installer/nativeLang/danish.xml        | 1616 ++++++++++----------
 PowerEditor/installer/nativeLang/french.xml        |    2 +-
 PowerEditor/installer/nativeLang/spanish.xml       |    6 +-
 PowerEditor/installer/nativeLang/tajikCyrillic.xml |  935 +++++++++++
 PowerEditor/installer/nppSetup.nsi                 |   36 +-
 PowerEditor/installer/packageAll.bat               |    4 -
 PowerEditor/src/MISC/Common/Common.cpp             |  133 +-
 PowerEditor/src/MISC/Common/Common.h               |   10 +-
 PowerEditor/src/Notepad_plus.cpp                   |    2 +-
 PowerEditor/src/NppCommands.cpp                    |    2 +-
 .../src/ScitillaComponent/ScintillaEditView.cpp    |   40 +-
 .../src/ScitillaComponent/ScintillaEditView.h      |    2 +-
 PowerEditor/src/langs.model.xml                    |    2 +-
 PowerEditor/src/localizationString.h               |  Bin 10416 -> 10508 bytes
 PowerEditor/src/resource.h                         |    6 +-
 24 files changed, 2018 insertions(+), 1149 deletions(-)
 delete mode 100644 PowerEditor/bin/updater/License.txt
 delete mode 100644 PowerEditor/bin/updater/readme.txt
 create mode 100644 PowerEditor/installer/nativeLang/tajikCyrillic.xml

AlexanderRiccio@ALEXANDERLAPTOP ~/Documents/GitHub/notepad-plus-plus (donho/master)
$ git status
On branch donho/master
Your branch is up-to-date with 'remotes/donho/master'.

nothing to commit, working directory clean

AlexanderRiccio@ALEXANDERLAPTOP ~/Documents/GitHub/notepad-plus-plus (donho/master)
$ git checkout master
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.

AlexanderRiccio@ALEXANDERLAPTOP ~/Documents/GitHub/notepad-plus-plus (master)
$ git merge donho/master
warning: refname 'donho/master' is ambiguous.
warning: refname 'donho/master' is ambiguous.
Updating c3c0cc4..5c272a8
Fast-forward
 .gitignore                                         |    1 +
 PowerEditor/bin/change.log                         |   20 +-
 PowerEditor/bin/readme.txt                         |   12 +-
 PowerEditor/bin/updater/GUP.exe                    |  Bin 135168 -> 135168 bytes
 PowerEditor/bin/updater/License.txt                |  165 --
 PowerEditor/bin/updater/gup.xml                    |   43 +-
 PowerEditor/bin/updater/libcurl.dll                |  Bin 262144 -> 288256 bytes
 PowerEditor/bin/updater/readme.txt                 |   60 -
 PowerEditor/installer/nativeLang/czech.xml         |   70 +-
 PowerEditor/installer/nativeLang/danish.xml        | 1616 ++++++++++----------
 PowerEditor/installer/nativeLang/french.xml        |    2 +-
 PowerEditor/installer/nativeLang/spanish.xml       |    6 +-
 PowerEditor/installer/nativeLang/tajikCyrillic.xml |  935 +++++++++++
 PowerEditor/installer/nppSetup.nsi                 |   36 +-
 PowerEditor/installer/packageAll.bat               |    4 -
 PowerEditor/src/MISC/Common/Common.cpp             |  133 +-
 PowerEditor/src/MISC/Common/Common.h               |   10 +-
 PowerEditor/src/Notepad_plus.cpp                   |    2 +-
 PowerEditor/src/NppCommands.cpp                    |    2 +-
 .../src/ScitillaComponent/ScintillaEditView.cpp    |   40 +-
 .../src/ScitillaComponent/ScintillaEditView.h      |    2 +-
 PowerEditor/src/langs.model.xml                    |    2 +-
 PowerEditor/src/localizationString.h               |  Bin 10416 -> 10508 bytes
 PowerEditor/src/resource.h                         |    6 +-
 24 files changed, 2018 insertions(+), 1149 deletions(-)
 delete mode 100644 PowerEditor/bin/updater/License.txt
 delete mode 100644 PowerEditor/bin/updater/readme.txt
 create mode 100644 PowerEditor/installer/nativeLang/tajikCyrillic.xml

AlexanderRiccio@ALEXANDERLAPTOP ~/Documents/GitHub/notepad-plus-plus (master)
AlexanderRiccio@ALEXANDERLAPTOP ~/Documents/GitHub/notepad-plus-plus (master)
$ git status
On branch master
Your branch is ahead of 'origin/master' by 26 commits.
  (use "git push" to publish your local commits)

nothing to commit, working directory clean

AlexanderRiccio@ALEXANDERLAPTOP ~/Documents/GitHub/notepad-plus-plus (master)
$ git push --verbose
Pushing to https://github.com/ariccio/notepad-plus-plus.git
Counting objects: 272, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (78/78), done.
Writing objects: 100% (198/198), 208.06 KiB | 0 bytes/s, done.
Total 198 (delta 154), reused 164 (delta 120)
POST git-receive-pack (213218 bytes)
To https://github.com/ariccio/notepad-plus-plus.git
   c3c0cc4..5c272a8  master -> master
updating local tracking ref 'refs/remotes/origin/master'

AlexanderRiccio@ALEXANDERLAPTOP ~/Documents/GitHub/notepad-plus-plus (master)
$
```

**Comment by ariccio** [comment]
By the way, a rebase is actually a better way to do it, but rebasing is, for some people (like me) not quite a habit yet.

...and while you have a shell open, it's probably a good idea to run a `git fsck --full`, just to make sure nothing is broken.

**Comment by MAPJe71** [comment]
Still getting used to Git (and TortoiseGit).
Been using SVN (and TortoiseSVN) for several years now which was a huge improvement over Visual SourceSafe.

**Pull request closed without merging**
