### PR TITLE
x64 build

### PR DESCRIPTION
**Pull request by NN---**
#64 Work in progress on x64 build.

### CODE REVIEW

**Comment by donho** [comment]
There is no way to integrate a development of a feature progressively.
You would work on it on your clone repository and do the pull request once the feature implementation is done.

**Comment by NN---** [comment]
I just have been advised to make smaller pull requests.
If you want a big one, it is not a problem.
Please follow up my changes and tell me if you have any comments.
Thanks .

**Comment by donho** [comment]
The guide lines (https://notepad-plus-plus.org/news/notepad-plus-plus-on-github.html) avoid that several features in a pull request. I do understand that a feature like 64 bits will be surely a big patch.

**Comment by ariccio** [comment]
Wait, why were we using `int` for `SendDlgItemMessage` & `SendMessage` to begin with?? LRESULT isn't new....if I remember correctly, It dates back to the days of 16-bit windows!

**Comment by NN---** [comment]
Technically in Win32 LRESULT=LONG_PTR=long and it has the same size of int.
So in Win32 these types are interchangeable .
Only in Win64 there is a difference LRESULT=LONG_PTR=long long .

**Comment by ariccio** [comment]
> Technically in Win32 LRESULT=LONG_PTR=long and it has the same size of int.

Yes, you are correct there.

> So in Win32 these types are interchangeable

No, not really. As a long time reader of [`The Old New Thing`](http://blogs.msdn.com/b/oldnewthing/), I absolutley refuse to say they're interchangable. 

Yes, the code will *probably* work, but that's essentially a coincidence.  *When* Microsoft changes the implementation of `LRESULT`, any code that assumes `LRESULT` is interchangeable with `int` or `long` needs to be carefully reviewed. We should (try to) never rely on implementation details.

That's **the** *raison d'être* of `LRESULT`.

**Comment by NN---** [comment]
@ariccio I was talking generally , if you want to be strict then I agree int and long are different types :)

**Comment by ariccio** [comment]
Oh no I totally see that you meant it generally, but my strictness and specificity are intentional, to ensure clarity.

**Pull request closed without merging**
