### PR TITLE
Fixed 25 instances of local variable shadowing.

### PR DESCRIPTION
**Pull request by ariccio**
file name                   | number of local variable shadowing instances
---------------------------|----------------
Parameters.cpp         |15 instances
Notepad_plus.cpp     | 3  instances
AutoCompletion.cpp  | 3  instances
Buffer.cpp                  | 2  instances
WordStyleDlg.cpp      | 1  instance
NppIO.cpp                 | 1  instance

### CODE REVIEW

**Comment by Rikk** [comment]
lol
Do anyone else see no need for this kind of changes?

**Comment by donho** [comment]
I just don't see any advantage in this patch.

**Comment by NN---** [comment]
VS2015 complains on shadowing variables and functions.
There are two choices either to fix it or just suppress the warning.
In general it is better to use different names.
It helps the reader easier to understand the code.

**Comment by Rikk** [comment]
Imo, it is much more readable to have a counter named "i" than "langArrayIdx", for example.
```
for (int i = 0 ; i < nbMax ; ++i) langArray[i] = false;
```
```
for (int langArrayIdx = 0 ; langArrayIdx < nbMax ; ++langArrayIdx) langArray[langArrayIdx] = false;
```

**Comment by NN---** [comment]
"i" is good name for counter but shadowing can make bugs

```cpp
for (int i = 0; i < x; ++i)
{
 for (int j = 0; j < x; ++j)
 {
   cout << j; // Okay "j" is in the inner loop
 }
 ... // some code
 for (int i = 0; i < x; ++i)
 {
   cout << i; // Which "i" ?
 }
}
```

**Comment by Rikk** [comment]
In that case, another letter would be welcome -- not a "iveAfukingBigName".
I dunno in C++, but in ES6 there would be a type "let" -- instead of "var" -- that would restrict the variable scope to the loop...

**Comment by MAPJe71** [comment]
for ( int idxOuter = 0; idxOuter < x; ++idxOuter )
    {
        int idxInner( 0 );
        for ( ; idxInner < x; ++idxInner )
        {
            cout << idxInner;
        }
        ... // some code
        idxInner = 0;
        for ( ; idxInner < x; ++idxInner )
        {
            cout << idxInner;
        }
    }

**Comment by ariccio** [comment]
@MAPJe71 +1

**Comment by ariccio** [comment]
Fun fact:

[Python loop variables leak into the enclosing scope(s)](http://eli.thegreenplace.net/2015/the-scope-of-index-variables-in-pythons-for-loops/)

**Pull request closed without merging**
