### PR TITLE
Even more sort fixes

### PR DESCRIPTION
**Pull request by andreas-jonsson**
Instead of guessing when a user wants a lexicographic sort vs a numeric sort, I have added options in the menu. There are now different choices for:

* lexicographic sort,
* integer sort,
* decimal sort with '.' as the decimal separator, and
* decimal sort with ',' as the decimal separator.

There are [a lot of different ways](http://en.wikipedia.org/wiki/Decimal_point#Examples_of_use) to specify a decimal number and I have only implemented the two most common ones.

Since the users now tell us what to do (instead of us trying to guess their intention) we can make the number parsing a bit more flexible. So "123abc" will be interpreted as "123" when doing a numeric sort. This allows for the case which [Guy Thevenot](https://sourceforge.net/p/notepad-plus/discussion/331753/thread/942efd7d/) wanted:

```
8        Alan                   1            Bob
1        Bob                    4            Edward
47       Charles                8            Alan
127      David        HOW ?     12           Harold
4        Edward       ¯¯¯       47           Charles
1000     Fred                   89           Gary
89       Gary                   127          David
12       Harold                 1000         Fred
```

Some implementation notes:

- I know Don doesn't like const, but if a function takes TCHAR* then it's very difficult to pass a generic_string to it. That's why I changed NativeLangSpeaker::messageBox to take const TCHAR* instead.
- Generally I would not put the entire implementation of a class in a header, but due to the way templates work this is necessary for NumericSorter (see Sorter.h). And since the things which *could* go in a .cpp file ended up being much less than the things I *had* to put in the header, I thought it would be easier to just put everything in the header.
- At one point I throw a size_t (in NumericSorter::sort). Again, not something I'd normally do, but it's a lot easier than using several out arguments in this case (we want to inform the user which line is causing the error. You can trigger an error by doing a numeric sort where one of the lines is really long.)
- There is a speed improvement when doing integer sorting (about 30%) compared to before. Amusingly when doing integer/decimal sorting most of the time is actually not spent sorting, but converting strings to numbers.

### CODE REVIEW

**Comment by MAPJe71** [comment]
Case sensitive vs. insensitive sort?

**Comment by andreas-jonsson** [comment]
It's a good idea and easy to implement. But I'll wait and see what Don says, I don't want to get this PR closed because it adds too many options to the menus.

**Comment by Rikk** [comment]
Any other name for "Lexicographic"? I think many users don't know what a "Lexicographic" sort is, and in what it differs from the others. Which ones can sort only text or only numbers?

**Comment by andreas-jonsson** [comment]
I'm open for suggestions, but I don't know a better term to describe it than "lexicographic". Maybe just "text"...

**Comment by xylographe** [comment]
Possible synonyms for lexicographic(al) order: dictionary order, alphabetical order.
But, I would stick with lexicographic or lexicographical.

**Comment by andreas-jonsson** [comment]
Don't know if there is an actual policy, but if someone still uses VS2010 and it can be supported by changing a single loop, why not?

**Comment by ariccio** [comment]
I'm totally fine with a single loop, but either way, the policy **should** be documented. If we support VS2010, then we can't really use `override`/`final`, `std::atomic`, and a whole bunch of scattered good things.

Here's an interesting idea: restrict VS2010 (and older) backwards compatibility to plugin-facing-headers *only*, so if a plugin ~~is broken enough that it~~ requires an older version of Visual Studio, it'll still compile. That'd leaves the rest of the codebase unbridled.

**Comment by crayxt** [comment]
I commented about build issues in VS2010 (https://github.com/donho/notepad-plus-plus/commit/dd846658e6599ba2878a0fbed3c0c2e8891abbe2). If supporting such old tool is limiting the project in any way, I agree that VS2010 support isn't needed. I'll figure out a way to install VS2013. Thanks,

**Comment by andreas-jonsson** [comment]
Another idea I had was that if the user makes a rectangular selection (Alt + select), then only the selected part will be used when sorting.

E.g if only the column with the numbers has been selected here:

```
a3
b2
c1
```

Then the result of an ascending integer sort will be:

```
c1
b2
a3
```

**Comment by crayxt** [comment]
@andreas-jonsson I asked similar question from a plugin developer https://github.com/blumu/NppColumnSort/issues/1

**Comment by MAPJe71** [comment]
You could also use an 'option' menu entry for enable/disable ascending sort to reduce the number of entries e.g. 

        :
       Split Lines
       Join Lines
       Move Up Current Lines
       Move Down Current Lines
        :
       Insert Blank Line Above Current
       Insert Blank Line Blow Current
    ----------------------------------------- (SEPARATOR)
       Sort Lines Lexicographically
       Sort Lines Integer
       Sort Lines Decimal (comma)
       Sort Lines Decimal (dot)
    ----------------------------------------- (SEPARATOR)
    v  Sort Ascending
    v  Sort Case Insensitive

**Comment by xylographe** [comment]
I think, the ascending/descending checkbox menu item makes sense (default ascending). But, the case sensitivity applies only to lexical sorting. Hence, perhaps,
```
<other stuff>
----------------------------------------- (SEPARATOR)
   Sort Lines Lexical (Case Sensitive)
   Sort Lines Lexical (Case Insensitive)
   Sort Lines Numerical (Integer)
   Sort Lines Numerical (Decimal dot)
   Sort Lines Numerical (Decimal comma)
----------------------------------------- (SEPARATOR)
□  Sort Descending
```
Possible enhancement: choice between ordinal, invariant-culture, and current-culture lexical sort.

**Comment by andreas-jonsson** [comment]
My objections to the checkbox:

* It is preferable to have as little state as possible in the UI. If a user selects menu option X, then Y should always happen.
* Don's suggestion has 8 options, xylographe's has 6. That's not a lot of options saved.
* Users might not understand that clicking "Sort Descending" just changes the setting. They might think it will actually perform a sort.
* If you are in descending mode and want to sort ascending, then you have to first deselect descending, then open the menu again and select the sort option you want. Too many clicks.

----------------

The main problem I have with Don's suggestion is that it repeats "Sort Lines" so many times. I think we should either remove one level of menus:

one

Or we should have sort lines directly under Edit:

two

**Comment by MAPJe71** [comment]
@andreas-jonsson  I would rename 'Edit > Sort Lines' to 'Edit > Sort Operations'.

**Comment by andreas-jonsson** [comment]
Maybe, if we are married to having "operations" in the Edit menu. The problem is that it doesn't make sense in English:

```
Sort Operations - Lexicographically, Ascending
```

Read it out loud and compare with:

```
Sort Lines - Lexicographically, Ascending
```

If we use "Sort Operations" then we have put the same verb first in all options, either

```
Sort Operations - Sort Lexicographically, or
Sort Operations - Sort Lines Lexicographically etc.
```

Annoying repetition.

**Comment by MAPJe71** [comment]
Yep, it 'sounds' better. 
We should have a closer look at the other sub menus to e.g.

    Copy to Clipboard > Current Full File path to Clipboard
                        Current Filename to Clipboard
                        Current Dir. Path to Clipboard
    Indent > Increase Line Indent
             Decrease Line Indent
    Line Operations > Duplicate Current Line
                      Split Lines
                      Join Lines
                      Move Up Current Line
                      Move Down Current Line
                      etc.

should then IMO be:

    Copy to Clipboard > Current File's Full Path
                        Current File's Name
                        Current File's Directory Path
    Indent > Increase
             Decrease
    Line Operations > Duplicate Current
                      Split
                      Join
                      Move Up Current
                      Move Down Current

But this should probably be a separate PR.

**Comment by donho** [comment]
@andreas-jonsson 
For me, Sort lines commands are Lines operations, so it should be submenu items of Lines Operations.
The 3 levels menu is still difficult to use.
I suggest:
...
Split Lines
Join Lines
Move Up Current Lines
Move Down Current Lines
...
Insert Blank Line Above Current
Insert Blank Line Blow Current
----------------------------------------- (SEPARATOR)
Sort Lines Lexicographically Ascending
Sort Lines As Integer Ascending
Sort Lines As Decimal (comma) Ascending
Sort Lines As Decimal (dot) Ascending
----------------------------------------- (SEPARATOR)
Sort Lines Lexicographically Descending
Sort Lines As Integer Descending
Sort Lines As Decimal (comma) Descending
Sort Lines As Decimal (dot) Descending

It's not a problem to me that "Sort Line" being repeated.
At least it'll be clear for users.

**Comment by andreas-jonsson** [comment]
Ok, see latest commit.

**Comment by donho** [comment]
> I know Don doesn't like const, but if a function takes TCHAR* then it's very difficult to pass a generic_string to it. That's why I changed NativeLangSpeaker::messageBox to take const TCHAR* instead.

lol! It's not I don't like costant. I like it when it is reasonably used (like in this case that I've forgotten it).

**Comment by Rikk** [comment]
My idea is something like this:
menu-mockup

**Comment by donho** [comment]
@Rikk IMO, it's quite complicated to use it.

**Comment by Rikk** [comment]
> @Rikk IMO, it's quite complicated to use it.
Do you mean complicated to code it? Or for the user to understand?
Well, in my opinion it looks much cleaner and thus easier than a lot of (redundant) lines and words. Even more because "Textually (lexicographically)" looks clearer than just "Lexicographically".

**Comment by andreas-jonsson** [comment]
I guess this is all a bit moot now that the PR has been merged, but I personally find it highly unintuitive to use menu options like this (as a user). I think I've only ever seen anything like it once before, and that is the "Begin/End Select" feature in N++ (coincidentally, it was I who coded that and now realize that it would be better if it was split into "Begin Select" and "End Select").

**Comment by ariccio** [comment]
By the way, if anybody needs to do profiling, I have a copy of vTune, and will happily run tests with it.

**Comment by Rikk** [comment]
>a menu checkbox which only refers to something in its own menu

I think the correct in my idea it could be radio buttons (meaning: you can select only one) in both lists:
menu-mockup2

Btw, I really think Npp menus are a mess and need some rethink. Commands which many options such as this one might deserve configuration in a dedicated panel in Settings.
Also, for those thinking my idea is hard to use... well, it is already hard to find many things inside all these big menus Npp have (... and without icons).

**Comment by andreas-jonsson** [comment]
@Rikk Two radio buttons? But what does the second one signify? Is "Textually (lexicographically)" an action ("it sorts") or an option ("it affects later actions")?

And going into *settings* for sorting? No way! Talk about being hard to find.

I think if cleaning up the menus is the goal (and it is a worthy one), then we should have a single command in the menu called "Sort" which pops up a modal dialog. The dialog should have two comboboxes (one for ascending/descending, and another for type of sort) and OK/Cancel buttons.

@ariccio I think all editions of VS include a profiler now (at least the free Community Edition does). That's what I used to guide the development of the sorting improvements.

**Comment by Rikk** [comment]
@andreas-jonsson What is hard to understand? One is the sort direction: asc/desc. The other is the variant of sort; all variants support both asc/desc directions as I see from above posts, therefore I see no need to duplicate each variant just for indicating the direction.

**Comment by andreas-jonsson** [comment]
> What is hard to understand?

What does the second radio button *mean*? In your screenshot, are Textually/Numerically all *settings*? If not, why is there a radio button in front of them? To avoid confusion, this is the one I can't figure out:

694401a6-033e-11e5-92cd-1735ac5496f6

**Comment by MAPJe71** [comment]
Uhm, also if the menu only contains 'settings' how do you actually start a sort?

**Comment by Rikk** [comment]
kind of... ooops

**Comment by janschreiber** [comment]
I agree with andreas-jonsson that a modal dialog would be the clearest solution.

**Pull request merged**
