### PR TITLE
Use precompiled headers correctly.

### PR DESCRIPTION
**Pull request by NN---**
Improve build speed.

### CODE REVIEW

**Comment by ariccio** [comment]
Numbers?

(I'm guessing, obviously, that it's less than ~2:50)

**Comment by NN---** [comment]
You can try on your own machine.
The previous setting was just wrong.
It actually compiled **each** file as precompiled header !
In that situation even removing it would lead to faster building time.
I didn't measure but now I am able to build without need of switching to other application.

**Comment by ariccio** [comment]
No, I trust you; but numbers are always good.

**Comment by NN---** [comment]
Release build
Before: 3:30
After: 1:02

**Comment by ariccio** [comment]
Fantastic.

**Comment by ariccio** [comment]
I'm sure that there are lots of related improvements -- there are repetitive lots of `#include`s in implementation files.

**Comment by NN---** [comment]
#pragma once is the best solution for this.
.
But it deserves another PR.

**Comment by ariccio** [comment]
> But it deserves another PR.

Agreed.

**Comment by rcdailey** [comment]
Personally I would not recommend using precompiled headers.

I recommend enabling parallel builds (`/MP`). You can get up to 8 translation units compiling simultaneously with 8 logical CPUs. Note that during on `/MP` requires turning off `/Gm` and precompiled headers.

**Comment by rcdailey** [comment]
@NN--- also `#pragma once` does not fix repetitive include directives, that just boils down to lack of proper inclusion management. Also not to mention `#pragma` directives are by-design platform defined. So using them in C++ runs the risk of making the code less portable.

**Comment by NN---** [comment]
@rcdailey Currently Notepad++ does use precompiled headers and I want to make the usage correct.
Precompiled headers are used for faster builds and it has mostly standard headers.
I do agree that you can make some abuse and forget to include headers in the correct order.
It is not hard to add explicit includes in the needed places.

Notepad++ is not portable anyway , so #pragma once is not a problem. :)
It doesn't fix repetitive includes but it makes second include as no-op.
Moreover all compilers today support #pragma once.
To make it portable it is easy:
```
#if VC or GCC or ICC or CLANG
#pragma once
#endif
```

**Comment by rcdailey** [comment]
@NN--- I understand that there is broken/incomplete support for PCH in the current setup. I am recommending you remove all remaining signs of PCH usage.

I understand what precompiled headers are for. The performance gain is not worth the maintenance burden.

Yes you can add includes where you think they might be needed but the compiler will not help you in the effort. If you introduce new symbols in a file and forget to add a corresponding set of `#include` directives, the compiler will not help you remember when you have PCH enabled.

Doesn't matter if Notepad++ isn't currently portable. Also portability means many things: Not necessarily platform (Linux, Mac OS), but toolchain (GCC or Clang on Windows; Cygwin). Also a portion of Notepad++ may be usable outside of Windows. As I stated before, what if that code needs to be turned into some sort of small library for another project?

You can never know where your C++ code may end up 10 years from now. But the main goal should always be to follow the C++ standard and do things as portable and correct as possible.

Also your example code makes zero sense and is counter productive. It's much clearer to just use include guards and be done with it.

Anyway my suggestion still stands: Use multiprocessor build configuration, disable PCH, profit.

**Comment by donho** [comment]
On my Windows 8.1 32bits machine is rather:
before vs after => 1:13 vs 1:01
12 seconds still count.

**Comment by rcdailey** [comment]
@donho Have you done a test with `/MP` on?

**Comment by milipili** [comment]
pragma once is supported by nearly all compilers.

**Comment by NN---** [comment]
Can you merge this PR because it takes too much time for to compile ? After then we will discuss how to speed up compilation.

**Comment by NN---** [comment]
@rcdailey include guards are not the same as #pragma once.
Pragma once doesn't allow you to check whether file was included by checking include guard definition.
Include guards don't optimize multiple include of the same file (whether directly or indirectly).
You must use both .

**Comment by rcdailey** [comment]
@NN--- Not true, some compilers have documented optimizations in compile time when using include guards. Some also optimize on `#pragma once`. Either way it's implementation defined. You could use both, but it's unconventional and extra maintenance for very little (if any) benefit. There is nothing that states you *must* use both. That's your personal preference.

If the code base is already using include guards, then keep using them. If it's using `#pragma once`, then keep using it. If you have a special need (like checking if a header has been included), you can choose include guard for that instead of the pragma.

@donho Please hold off on merging this as I plan to do a PR that enables multiprocessor build and eliminates usage of PCH. I will provide timing results as well.

Again I want to caution the impact of enabling PCH. Dependency management will no longer be compiler-enforced and will significantly degrade over time.

**Comment by NN---** [comment]
I did measurements and VC compiles faster with pragma once.
I didn't measure VC2013 but I doubt it changed.
Same for precompiled headers. They do speed up compilation if you use them correctly.
I don't see any reason why not to use both.
Precompiled headers have only non modifiable includes like standard library so you don't really mess with dependencies .
I want this PR merged to create new ones easier. 3 minutes of compilation time is too much when after this change I get 1 minute.

I am not against your proposal but yours is a long term solution while mine is a short term until you measure all possibilities and propose the one with best compilation times.
I do encourage you to measure with pragma once as well to see whether it helps or makes compilation time worse.
Thanks.

**Comment by rcdailey** [comment]
Please see PR #90 for a change I made to enable parallel builds. Build times I've observed is 1 second longer than PCH but does not come with the maintenance burden that PCH brings.

@NN--- I'm not going to debate `#pragma once` vs include guards here, it's off topic. If you want to improve build times so you can move on to other tasks, I recommend you take a look at PR #90 and run some tests on your own machine and measure the differences.

If you also find performance improvements using `#pragma once`, by all means introduce that change but this specific concern I have is with project configuration only.

**Comment by NN---** [comment]
Closing.
Use #90

**Pull request closed without merging**
