### PR TITLE
Update to sqlite 3 8 10 2

### PR DESCRIPTION
**Pull request by chcg**
Update sqlite from 3.8.5 to current 3.8.10.2, from https://www.sqlite.org/2015/sqlite-amalgamation-3081002.zip

### CODE REVIEW

**Comment by chcg** [comment]
Just saw #14 on this.

**Comment by damien-gerard** [comment]
SQLite will have to be updated anyway. But probably in a future release.

**Comment by don4d** [comment]
I confirm what @damien-gerard  said: sqllite will be upgraded in the future version of Notepad++.

**Comment by donho** [comment]
I confirm what @damien-gerard said: sqllite will be upgraded in the future version of Notepad++.

**Comment by Rikk** [comment]
If no changes are made to sqlite, a suggestion is to set it as a git submodule, then only one or two git commands will be needed to update it...
https://git-scm.com/book/en/v2/Git-Tools-Submodules
http://johnleach.co.uk/words/323/git-submodules-in-n-easy-steps

**Pull request closed without merging**
