### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by stenox**
Update with new strings from EN

### CODE REVIEW

**Comment by ariccio** [comment]
I don't think that Don Ho accepts PRs, as he mentioned in a comment:
https://sourceforge.net/p/notepad-plus/patches/656/#88ee/33da/fb13/55d4/2415/9056/2628/e6e7

The link seems broken, the comment is on the second page:

> github repo was created few days ago.
> And the push request is not accepted on github.
> I will find a better way to do that.


I wish he did too ;)

**Comment by ariccio** [comment]
...on the other hand: https://github.com/donho/notepad-plus-plus/pull/1

**Comment by donho** [comment]
ariccio, I think I will give it a try. Then I will sse.

**Comment by donho** [comment]
stenox:
could you please make 1 commit instead of 3?

**Comment by Fitoschido** [comment]
This is how to squash commits: basically using interactive rebase. http://stackoverflow.com/questions/14534397/squash-all-my-commits-into-one-for-github-pull-request

Force-pushing is needed since GitHub won’t accept a normal push in that case.

**Pull request merged**
